# Site settings
title: tristangriffiths.net
title_separator: "|"
description: The personal blog of Tristan Griffiths - IT Jebus
encoding: utf-8

# Build settings
markdown: kramdown
# Outputting
permalink: /:title
paginate: 5 # amount of posts to show
paginate_path: /page:num
timezone: "Australia/Melbourne"

include: 
    - _pages

# Exclude from processing
exclude: 
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: text-page
  - scope:
      path: "assets/img"
    values:
      image: true