# Site settings
title: tristangriffiths.net
description: The personal blog of Tristan Griffiths - IT Jebus
twitter_username: 
github_username: monkeyatcomputer
minimal_mistakes_skin: default
encoding: utf-8

# Build settings
markdown: kramdown
# Outputting
permalink: /:title
paginate: 5 # amount of posts to show
paginate_path: /page:num
timezone: "Australia/Melbourne"

include: 
    - _pages

# Exclude from processing
exclude: 
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Tristan Griffiths"
  avatar: ""
  bio: ""
  links:

footer:
  links:

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
  - scope:
      path: "assets/img"
    values:
      image: true