# General Jekyll Config
highlighter: rogue
name: tristangriffiths.net
description: The personal blog of Tristan Griffiths - IT Jebus
remote_theme: daattali/beautiful-jekyll
url: "https://tristangriffiths.net"
encoding: utf-8

exclude: [LICENSE, CNAME, README.md, .gitignore, Genfile, Genfile.locl]

# Build settings
permalink: pretty